In [1]:
import tensorflow as tf

In [3]:
B, K, N = 2, 2, 2
inputs = tf.random.uniform(shape=[B, K, N], minval=0, maxval=10)
print(inputs)

tf.Tensor(
[[[1.2421572 5.21603  ]
  [1.33865   9.073278 ]]

 [[7.086942  9.805056 ]
  [9.5442915 5.9516134]]], shape=(2, 2, 2), dtype=float32)


In [4]:
gamma = tf.random.uniform(shape=[1, N])
beta = tf.random.uniform(shape=[1, N])
print('gamma: ', gamma)
print('beta:', beta)

gamma:  tf.Tensor([[0.09098339 0.78476334]], shape=(1, 2), dtype=float32)
beta: tf.Tensor([[0.6133505  0.38725078]], shape=(1, 2), dtype=float32)


In [ ]:
_K = inputs.shape[-2]
_count = tf.reshape(range(1, _K+1), [1, _K, 1])
_count = tf.cast(_count, tf.float32)

_H_mean = tf.reduce_mean(inputs, axis=-1, keepdims=True)
_H_pow_mean = tf.reduce_mean(tf.pow(inputs, 2), axis=-1, keepdims=True)

_sum = tf.cumsum(_H_mean, axis=-2)
_pow_sum = tf.cumsum(_H_pow_mean, axis=-2)

_mean = _sum / _count
_var = (_pow_sum - 2*_mean*_sum) / _count + tf.pow(_mean, 2)

outputs = self.gamma * ((inputs - _mean) /
                    tf.sqrt(_var + self.eps)) + self.beta